### ISSUE TITLE
using randomly selected plotting channels vs. creating reports

### ISSUE THREAD

**Issue by rgutzen** [INM-6/wavescalephant#18]
The config files of each stage specify `PLOT_CHANNELS` which can be set to a scalar of list of `int` or `None`, where `None` is replaced by a randomly chosen channel id at the beginning of the Snakefile. When running the full pipeline this parameter is overwritten by the global plotting settings in the top-level config file. When this top-level config file contains `None`, the selection of channels and the plotting still works fine. However, once the reports are to be created the `None` entries are replaced again by newly chosen random channels. Thus, the reports generally request different plots then were generated and thus fail to be created.
Therefore, either don't use `None` in the top-level config file or expect the reports to not be created (the rest of the pipeline will be executed).

**Comment by gulpgiulia** [comment]
not fully sure I understood the point, but I believe that this should be mentioned at least in the comments of the top-level config.yaml . Currently, this setting is specified at line 23, with no mention of this issue: `PLOT_CHANNELS: 'None'  # int or None. default 'None' -> randomly selected`

**Comment by rgutzen** [comment]
You are right, so far it is only described in the pipeline readme. I will add a short note to the config file as well.
