### ISSUE TITLE
data_entry step fails with most IDIBAPS files

### ISSUE THREAD

**Issue by apdavison** [INM-6/wavescalephant#19]
I've been trying to run the pipeline with the files from https://kg.ebrains.eu/search/instances/Dataset/2ead029b-bba5-4611-b957-bb6feb631396

For most of the files, it fails with the error:
`AssertionError: Signal channel in groups do not have same size, use try_signal_grouping=False`

Such files have channels that differ slightly in length, e.g. 
```
ipdb> sig_sizes
array([638735, 638735, 638735, 638735, 638735, 638734, 638734, 638734,
       638734, 638734, 638734, 638734, 638734, 638735, 638735, 638735])
```

I think it would be fairly easy to adapt the `load_neo()` function so that it loads the data using `try_signal_grouping=False`, trims the signals to  a common length, and then 'manually' groups them.

**Comment by rgutzen** [comment]
You are right, the script _stage01_data_entry/scripts/curate_IDIBAPS_data.py_ tries to do exactly that. There was, however, still a small bug which should now be resolved.
Tested with WT subjects 32 channel recordings.

**Comment by rgutzen** [comment]
double checked with:
* Sanchez-Vives, M. (2020) "Propagation modes of slow waves in mouse cortex" EBRAINS
* Sanchez-Vives, M. (2019) "Cortical activity features in transgenic mouse models of cognitive deficits (Fragile X Syndrome)" EBRAINS
* Sanchez-Vives, M. (2019) "Cortical activity features in transgenic mouse models of cognitive deficits (Williams Beuren Syndrome" EBRAINS
