### ISSUE TITLE
Stage 02 - background_substraction: KeyError

### ISSUE THREAD

**Issue by araihC** [INM-6/wavescalephant#20]
At Stage02 of the pipeline, the execution exits with the error

```
Traceback (most recent call last):
  File "scripts/background_substraction.py", line 55, in <module>
    zip(asig.array_annotations['x_coords'],
KeyError: 'x_coords'
```
The error encountered means that the annotations from stage01 are not properly stored in the .nix output file. 
This is due to a previous bug in neo.

I solved this installing the right version of neo through the command

`pip install git+https://github.com/NeuralEnsemble/python-neo.git`

**Comment by rgutzen** [comment]
Because the installation of packages directly from GitHub does not reliably work with `conda env create -f`, there are now adapted instructions in the pipeline Readme regarding the two affected packages neo and elephant.
