### ISSUE TITLE
UnavailableInvalidChannel Error - Build the Python environment

### ISSUE THREAD

**Issue by araihC** [INM-6/wavescalephant#21]
As locally building the python environment to run the pipeline, an error occurred:

```
conda env create --file environment.yaml
Collecting package metadata: failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: biconda
  channel url: https://conda.anaconda.org/biconda
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

I solved the UnavailableInvalidChannel error (on creating a new environment) by
1.	starting Anaconda Navigator,
2.	clicking 'Environments',
3.	clicking button 'Channels' and
4.	removing the channel referring to my Downloads folder (only keeping 'defaults').

**Comment by rgutzen** [comment]
This looks like a local typo _biconda_ instead of _bioconda_. Could you check your environment.yaml file and if necessary correct the typo or pull a new repo version?
