### ISSUE TITLE
Stage 02 - ImportError

### ISSUE THREAD

**Issue by araihC** [INM-6/wavescalephant#22]
While executing the pipeline, Stage 02 exited with error
```
Traceback (most recent call last):
  File "scripts/roi_selection.py", line 6, in <module>
    from skimage import measure

```
I solved this issue installing the right version of scikit-image through conda-forge by running the command 
 
`conda install scikit-image --channel conda-forge`

**Comment by rgutzen** [comment]
This seems to be due to an outdated version of the repository, in which the package was still missing from the environment file. For tractability, please add the version of the repository (hash of latest commit) you are using to the Issue report.
