### ISSUE TITLE
Stage 01 - ValueError

### ISSUE THREAD

**Issue by araihC** [INM-6/wavescalephant#23]
When running the pipeline on some datasets (as the one provided by LENS), a ValueError occurs at stage 01:
 
`ValueError: Image size of 268559x437 pixels is too large. It must be less than 2^16 in each direction.`

I avoided it by changing: `bbox_inches=None` in utils.py

**Comment by rgutzen** [comment]
I remember this type of Error message. Although I don't recall the exact cause of it this should be fixed in the current version. Can you please pull again and check whether the error still occurs?
