### ISSUE TITLE
Improve top-level Readme

### ISSUE THREAD

**Issue by rgutzen** [INM-6/wavescalephant#8]

**Comment by rgutzen** [comment]
- add links to related repositories: 
https://github.com/gulpgiulia/ElePhySWAP_SOAP 
https://github.com/gulpgiulia/CaImanSWAP

**Comment by gulpgiulia** [comment]
Contents rearranged in view of reporting needs due by SGA2-M24. The last two paragraphs ("Repository structure" and "Snakemake workflow introduction") still need to be updated/checked.
[Editing issue: in paragraph "WaveScalEphant short- and mid- term goals", there is text in bold italic that shouldn't be such]
